"""Generate docs/writing/index.md and docs/feed.xml from post front matter.

Zensical (alpha) has no native blog plugin yet; this script fills the gap and
can be deleted once the native blog lands. Posts live in docs/writing/posts/
with YAML front matter: title, date (ISO), description, draft (optional).
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from datetime import date, datetime, time, timezone
from email.utils import format_datetime
from pathlib import Path
from xml.sax.saxutils import escape

import frontmatter

ROOT = Path(__file__).resolve().parent.parent
POSTS_DIR = ROOT / "docs" / "writing" / "posts"
INDEX_PATH = ROOT / "docs" / "writing" / "index.md"
FEED_PATH = ROOT / "docs" / "feed.xml"
FEED_LIMIT = 20


def load_site_url() -> str:
    config = tomllib.loads((ROOT / "zensical.toml").read_text())
    return config["project"]["site_url"].rstrip("/")


def load_posts(include_drafts: bool) -> list[dict]:
    posts = []
    for path in sorted(POSTS_DIR.glob("*.md")):
        post = frontmatter.load(path)
        missing = [k for k in ("title", "date", "description") if k not in post]
        if missing:
            sys.exit(f"error: {path.name} missing front matter keys: {missing}")
        if post.get("draft") and not include_drafts:
            continue
        post_date = post["date"]
        if not isinstance(post_date, date):
            post_date = date.fromisoformat(str(post_date))
        posts.append(
            {
                "title": str(post["title"]),
                "date": post_date,
                "description": str(post["description"]),
                "slug": path.stem,
                "path": path,
            }
        )
    posts.sort(key=lambda p: (p["date"], p["slug"]), reverse=True)
    return posts


def write_index(posts: list[dict]) -> None:
    lines = [
        "---",
        "title: Writing",
        "description: Articles on security operations, threat detection, incident response, and AI in the SOC.",
        "---",
        "",
        "<!-- GENERATED by scripts/generate_blog.py — do not edit by hand -->",
        "",
        "# Writing",
        "",
    ]
    if not posts:
        lines.append("*Nothing published yet — first articles are on their way.*")
    for post in posts:
        lines.append(f"## [{post['title']}](posts/{post['slug']}.md)")
        lines.append("")
        lines.append(f"*{post['date'].isoformat()}* — {post['description']}")
        lines.append("")
    INDEX_PATH.write_text("\n".join(lines).rstrip() + "\n")


def write_feed(posts: list[dict], site_url: str) -> None:
    now = format_datetime(datetime.now(timezone.utc))
    items = []
    for post in posts[:FEED_LIMIT]:
        url = f"{site_url}/writing/posts/{post['slug']}/"
        pub = format_datetime(
            datetime.combine(post["date"], time(9, 0), tzinfo=timezone.utc)
        )
        items.append(
            "  <item>\n"
            f"   <title>{escape(post['title'])}</title>\n"
            f"   <link>{escape(url)}</link>\n"
            f"   <guid isPermaLink=\"true\">{escape(url)}</guid>\n"
            f"   <pubDate>{pub}</pubDate>\n"
            f"   <description>{escape(post['description'])}</description>\n"
            "  </item>"
        )
    feed = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n'
        " <channel>\n"
        "  <title>Alexandru Hera — Writing</title>\n"
        f"  <link>{site_url}/writing/</link>\n"
        "  <description>Security operations, threat detection, incident response,"
        " and AI in the SOC.</description>\n"
        "  <language>en</language>\n"
        f"  <lastBuildDate>{now}</lastBuildDate>\n"
        f'  <atom:link href="{site_url}/feed.xml" rel="self"'
        ' type="application/rss+xml"/>\n'
        + "\n".join(items)
        + ("\n" if items else "")
        + " </channel>\n"
        "</rss>\n"
    )
    FEED_PATH.write_text(feed)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--drafts", action="store_true", help="include draft posts")
    args = parser.parse_args()

    POSTS_DIR.mkdir(parents=True, exist_ok=True)
    posts = load_posts(include_drafts=args.drafts)
    write_index(posts)
    write_feed(posts, load_site_url())
    print(f"generate_blog: {len(posts)} post(s) → writing/index.md, feed.xml")


if __name__ == "__main__":
    main()
